library(tidyverse)
library(magrittr)
datos <- read.csv("Limpia.csv", sep = ";",
                  encoding = "Latin-ASCII")
datos %<>%
  arrange(BARRIO)

# datos %<>%
#   mutate(
#     BARRIO = if_else(
#       BARRIO == "A\x81rea de Expansion Altavista",
#       "Área de Expansión Altavista",
#       BARRIO
#     ),
#     BARRIO = if_else(
#       BARRIO == "A\x81rea de Expansion Altos de Calasanz",
#       "Blanquizal",
#       BARRIO
#     ),
#     BARRIO = if_else(
#       BARRIO == "A\x81rea de Expansion Pajarito",
#       "Área de Expansión Pajarito",
#       BARRIO
#     ),
#     BARRIO = if_else(
#       BARRIO == "A\x81rea de Expansion San Antonio de Prado",
#       "Área de Expansión San Antonio de Prado",
#       BARRIO
#     ),
#     BARRIO = if_else(BARRIO %in% c("Aguas frias", "Aguas Frias"),
#                      "Aguas Frías", BARRIO),
#     BARRIO = if_else(BARRIO == "Alejandria", "Alejandría", BARRIO),
#     BARRIO = if_else(BARRIO == "Alejandro Echavarria", "Alejandro Echavarría",
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Alfonso Lopez", "Alfonso López", BARRIO),
#     BARRIO = if_else(BARRIO == "Altos del poblado", "Altos del Poblado", BARRIO),
#     BARRIO = if_else(BARRIO == "Andalucia", "Andalucía", BARRIO),
#     BARRIO = if_else(BARRIO == "Antonio Narino", "Antonio Nariño", BARRIO),
#     BARRIO = if_else(
#       BARRIO == "Area De Expansion Belen Rincon",
#       "Área de Expansión Belén Rincón",
#       BARRIO
#     ),
#     BARRIO = if_else(BARRIO == "Asomadera No. 1", "Asomadera No.1", BARRIO),
#     BARRIO = if_else(BARRIO == "Asomadera No. 2", "Asomadera No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Asomadera No. 3", "Asomadera No.3", BARRIO),
#     BARRIO = if_else(BARRIO == "B. Cerro  El Volador",
#                      "B. Cerro El Volador", BARRIO),
#     BARRIO = if_else(BARRIO == "Barrio Colon", "Barrio Colón", BARRIO),
#     BARRIO = if_else(BARRIO == "Barrio Cristobal", "Barrio Cristóbal", BARRIO),
#     BARRIO = if_else(BARRIO == "Barrio de Jesus", "Barrios de Jesús", BARRIO),
#     BARRIO = if_else(BARRIO == "Batallon Girardot", "Batallón Girardot", BARRIO),
#     BARRIO = if_else(BARRIO == "Belalcazar", "Belalcázar", BARRIO),
#     BARRIO = if_else(BARRIO == "Belen", "Belén", BARRIO),
#     BARRIO = if_else(BARRIO == "Berlin", "Berlín", BARRIO),
#     BARRIO = if_else(BARRIO == "Bermejal-Los Alamos",
#                      "Bermejal-Los Álamos", BARRIO),
#     BARRIO = if_else(BARRIO == "Bombona No. 1", "Bomboná No.1", BARRIO),
#     BARRIO = if_else(BARRIO == "Bombona No. 2", "Bomboná No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Boqueron", "Boquerón", BARRIO),
#     BARRIO = if_else(BARRIO == "Boyaca", "Boyacá", BARRIO),
#     BARRIO = if_else(
#       BARRIO == "Cabecera San Antonio de Prado",
#       "San Antonio de Prado",
#       BARRIO
#     ),
#     BARRIO = if_else(
#       BARRIO == "Cabecera Urbana San Cristobal",
#       "Cabecera Urbana Corregimiento San Cristóbal",
#       BARRIO
#     ),
#     BARRIO = if_else(BARRIO == "Campo amor", "Campo Amor", BARRIO),
#     BARRIO = if_else(BARRIO == "Campo Valdes No. 1" ,
#                      "Campo Valdés No.1",
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Campo Valdes No.2",
#                      "Campo Valdés No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Cataluna", "Cataluña", BARRIO),
#     BARRIO = if_else(BARRIO == "Corazon de Jesus",
#                      "Corazón de Jesús", BARRIO),
#     BARRIO = if_else(BARRIO == "Cordoba", "Córdoba", BARRIO),
#     BARRIO = if_else(BARRIO == "Diego Echavarria", "Diego Echavarría",
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "El Corazon", "El Corazón", BARRIO),
#     BARRIO = if_else(BARRIO == "El Corazon El Morro",
#                      "El Corazón El Morro", BARRIO),
#     BARRIO = if_else(BARRIO == "El Diamante No. 2",
#                      "El Diamante No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "El Estadio", "Estadio" , BARRIO),
#     BARRIO = if_else(BARRIO == "El poblado", "El Poblado", BARRIO),
#     BARRIO = if_else(BARRIO == "El Progreso No.2", "El Progreso", BARRIO),
#     BARRIO = if_else(BARRIO == "El Rincon", "El Rincón", BARRIO),
#     BARRIO = if_else(BARRIO == "El Velódromo", "El Velodromo", BARRIO),
#     BARRIO = if_else(BARRIO == "El Vergel", "Miraflores", BARRIO),
#     BARRIO = if_else(BARRIO == "Estacion Villa", "Estación Villa", BARRIO),
#     BARRIO = if_else(BARRIO == "Fatima", "Fátima", BARRIO),
#     BARRIO = if_else(BARRIO == "FLORIDA NUEVA", "Florida Nueva", BARRIO),
#     BARRIO = if_else(BARRIO == "Hector Abad Gomez",
#     "Héctor Abad Gómez", BARRIO),
#     BARRIO = if_else(BARRIO == "Hospital San Vicente de Paul",
#                      "Hospital San Vicente de Paúl", BARRIO),
#     BARRIO = if_else(BARRIO == "Jardin Botanico", "Jardín Botánico", BARRIO),
#     BARRIO = if_else(BARRIO == "Jesus Nazareno", "Jesús Nazareno", BARRIO),
#     BARRIO = if_else(BARRIO == "LA ALPUJARRA", "La Alpujarra", BARRIO),
#     BARRIO = if_else(BARRIO == "La America", "La América", BARRIO),
#     BARRIO = if_else(BARRIO == "La Esperanza No. 2",
#                      "La Esperanza No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "La loma de los Bernal",
#                      "La Loma de Los Bernal", BARRIO),
#     BARRIO = if_else(BARRIO == "La Loma Oriental", "El Socorro", BARRIO),
#     BARRIO = if_else(BARRIO == "La Mansion", "La Mansión", BARRIO),
#     BARRIO = if_else(BARRIO == "La mota", "La Mota", BARRIO),
#     BARRIO = if_else(BARRIO == "La Oculta", "El Poblado", BARRIO),
#     BARRIO = if_else(BARRIO == "La Pinuela", "La Piñuela", BARRIO),
#     BARRIO = if_else(BARRIO == "Las independencias",
#                      "Las Independencias", BARRIO),
#     BARRIO = if_else(BARRIO == "Las Lomas No. 2", "Las Lomas No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Lopez de Mesa", "López de Mesa", BARRIO),
#     BARRIO = if_else(BARRIO == "Los Alcazares", "Los Alcázares", BARRIO),
#     BARRIO = if_else(BARRIO == "Los Angeles", "Los Ángeles", BARRIO),
#     BARRIO = if_else(BARRIO == "Manrique Central No. 1",
#                      "Manrique Central No.1", BARRIO),
#     BARRIO = if_else(BARRIO == "Manrique Central No. 2",
#                      "Manrique Central No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Maria Cano Carambolas",
#                      "María Cano-Carambolas", BARRIO),
#     BARRIO = if_else(BARRIO == "Moscu No. 1", "Moscú No.1", BARRIO),
#     BARRIO = if_else(BARRIO == "Moscu No. 2", "Moscú No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Noel", "Cristo Rey", BARRIO),
#     BARRIO = if_else(BARRIO == "Nueva Villa de Aburra",
#                      "Nueva Villa de Aburrá", BARRIO),
#     BARRIO = if_else(BARRIO == "Nueva Villa de la Iguana",
#                      "Nueva Villa de la Iguaná", BARRIO),
#     BARRIO = if_else(BARRIO == "Patio  Bonito", "Patio Bonito", BARRIO),
#     BARRIO = if_else(BARRIO == "Pedregal Bajo", "Pedregal", BARRIO),
#     BARRIO = if_else(BARRIO %in% c("Piedras Blancas", "Piedras Blancas Represa"),
#                      "Piedras Blancas - Matasano", BARRIO),
#     BARRIO = if_else(BARRIO %in% c("Playon de los Comuneros",
#                                    "Playon de Los Comuneros"),
#                      "Playón de Los Comuneros", BARRIO),
#     BARRIO = if_else(BARRIO == "San antonio", "San Antonio", BARRIO),
#     BARRIO = if_else(BARRIO %in% c("San cristobal", "San Cristobal"),
#                      "Cabecera Urbana Corregimiento San Cristóbal", BARRIO),
#     BARRIO = if_else(BARRIO == "San German", "San Germán", BARRIO),
#     BARRIO = if_else(BARRIO == "San Joaquin", "San Joaquín", BARRIO),
#     BARRIO = if_else(BARRIO == "San Jose de la Montana",
#                      "San José de la Montaña", BARRIO),
#     BARRIO = if_else(BARRIO == "San Jose Del Manzanillo",
#                      "San José del Manzanillo", BARRIO),
#     BARRIO = if_else(BARRIO == "San Jose la Cima No. 1",
#                      "San José La Cima No.1", BARRIO),
#     BARRIO = if_else(BARRIO == "San Jose la Cima No.2",
#                      "San José La Cima No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "San Martin de Porres",
#                      "San Martín de Porres", BARRIO),
#     BARRIO = if_else(BARRIO == "San Sebastian de palmitas",
#                      "Palmitas Sector Central", BARRIO),
#     BARRIO = if_else(BARRIO == "Santa Fe", "Santa Fé", BARRIO),
#     BARRIO = if_else(BARRIO == "Santa Ines", "Santa Inés", BARRIO),
#     BARRIO = if_else(BARRIO == "Santa Lucia", "Santa Lucía", BARRIO),
#     BARRIO = if_else(BARRIO %in% c("Santa Maria de los Angeles", 
#                                    "Santa Maria de Los Angeles"), 
#                      "Santa María de Los Ángeles", BARRIO),
#     BARRIO = if_else(BARRIO == "Santa Monica", "Santa Mónica", BARRIO),
#     BARRIO = if_else(BARRIO == "Santa teresita", "Santa Teresita", BARRIO),
#     BARRIO = if_else(BARRIO == "Santo Domingo Savio No. 1", 
#                      "Santo Domingo Savio No.1", BARRIO),
#     BARRIO = if_else(BARRIO == "Santo Domingo Savio No. 2", 
#                      "Santo Domingo Savio No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Simon Bolivar", "Simón Bolívar", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Aguas Frias", "Aguas Frías", 
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Altavista", "Altavista", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano El Llano", "El Llano", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano El Plan", "El Plan", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano el Tesoro", "El Tesoro", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano La Cuchilla", "La Cuchilla", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano La Loma", "La Loma", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Mirador del Poblado", "El Poblado",
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Palma Patio", "La Palma", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Palmitas", "Palmitas Sector Central",
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Pedregal alto", "Pedregal Alto",
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Piedra Gorda", "Piedra Gorda", 
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Potrerito", "Potrerito", BARRIO),
#     BARRIO = if_else(BARRIO == "Suburbano Travesias", "Travesías", BARRIO),
#     BARRIO = if_else(BARRIO == "Travesia", "Travesías", BARRIO),
#     BARRIO = if_else(BARRIO == "U.P.B.", "U.P.B", BARRIO),
#     BARRIO = if_else(BARRIO %in% c("Urbanizacion loyola", 
#                                    "Urbanizacion Loyola"), "Miraflores", 
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Urbanizacion Plaza Vicuna", "Belén", BARRIO),
#     BARRIO = if_else(BARRIO == "Urbanización Torres del Estadio", "Estadio",
#                      BARRIO),
#     BARRIO = if_else(BARRIO == "Versalles No. 1", "Versalles No.1", BARRIO),
#     BARRIO = if_else(BARRIO == "Versalles No. 2", "Versalles No.2", BARRIO),
#     BARRIO = if_else(BARRIO == "Via a Santa Elena", 
#                      "Santa Elena Sector Central", BARRIO),
#     BARRIO = if_else(BARRIO == "Villa Liliam", "Villa Lilliam", BARRIO)
#   )

saveRDS(datos, "datosClustering.Rds")






